version: "3.9"

services:
  database:
    container_name: "database"
    image: mysql:latest
    ports:
      - "4000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sparking
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
